# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Doctorapp', '0001_initial'),
        ('ReceptionistApp', '0002_remove_batch_pharm_remove_consultation_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('LaboratoryId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=255)),
                ('TestResult', models.TextField()),
                ('ResultDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('sample_No', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Reffered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctorapp.doctorinform')),
                ('consultant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctorapp.consultation')),
                ('patientinform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_information', to='ReceptionistApp.patientdetails')),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('LabBillId', models.AutoField(primary_key=True, serialize=False)),
                ('DeviceCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ServiceCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TestingCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TotalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Reffered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctorapp.doctorinform')),
                ('patientinform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReceptionistApp.patientdetails')),
                ('LabTest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_bills', to='labtechnicianApp.labtest')),
            ],
        ),
    ]
