# Generated by Django 5.2 on 2025-04-03 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('AppointmentDate', models.DateTimeField()),
                ('Status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('Remarks', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabDevice',
            fields=[
                ('ModuleId', models.AutoField(primary_key=True, serialize=False)),
                ('EquipmentName', models.CharField(max_length=250)),
                ('Quantity', models.IntegerField()),
                ('Last_Service_Date', models.DateField()),
                ('Next_Service_Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(choices=[('working', 'Working'), ('undermaintenance', 'Under Maintenance'), ('standby', 'Standby'), ('outoforder', 'Out of Order')], default='working', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('DOb', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('BloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=20)),
                ('Address', models.TextField()),
                ('phonenumber', models.CharField(max_length=15)),
                ('EmergencyContact', models.CharField(max_length=15)),
                ('alergy', models.TextField(blank=True, null=True)),
                ('RegisterationDate', models.DateTimeField(auto_now_add=True)),
                ('LastVisitDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharm',
            fields=[
                ('MedicineId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Expiry_Date', models.DateField()),
                ('PricePerUnit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lowStock', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentBill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('Consultant_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ServiceCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
                ('Date_of_Birth', models.DateField()),
                ('Date_of_Joining', models.DateField()),
                ('EmailId', models.EmailField(max_length=254)),
                ('phone_Number', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Specialization', models.CharField(max_length=100)),
                ('Consultant_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.department')),
                ('UserId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.login')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.doctor'),
        ),
        migrations.CreateModel(
            name='LabDepartment',
            fields=[
                ('LabId', models.AutoField(primary_key=True, serialize=False)),
                ('EquipmentName', models.CharField(max_length=250)),
                ('Department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('LaboratoryId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=255)),
                ('TestResult', models.TextField()),
                ('ResultDate', models.DateTimeField(blank=True, null=True)),
                ('DeviceCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ServiceCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TestingCharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('LabDepartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.labdepartment')),
            ],
        ),
        migrations.CreateModel(
            name='LabBill',
            fields=[
                ('LabBillId', models.AutoField(primary_key=True, serialize=False)),
                ('TotalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('LabTest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='LabTesting',
            fields=[
                ('TestingId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=255)),
                ('Notes', models.TextField(blank=True, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.appointment')),
                ('Test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.labtest')),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('ConsultantId', models.AutoField(primary_key=True, serialize=False)),
                ('Notes', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.appointment')),
                ('LabTesting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.labtesting')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='PatientDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.patientdetails'),
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('RecordId', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.TextField()),
                ('Treatment', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('BatchId', models.AutoField(primary_key=True, serialize=False)),
                ('ManufacturingDate', models.DateField()),
                ('Pharm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.pharm')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('PharmId', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('PricePerUnit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Pharm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.pharm')),
            ],
        ),
        migrations.CreateModel(
            name='PharmBill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('TotalPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.pharmacist')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=100)),
                ('No_of_Days', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.appointment')),
                ('Medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.pharm')),
            ],
        ),
        migrations.AddField(
            model_name='consultation',
            name='Prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.prescription'),
        ),
        migrations.AddField(
            model_name='login',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.role'),
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('SignupID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('EmailId', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=15)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.role')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='Signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.signup'),
        ),
        migrations.CreateModel(
            name='StaffManage',
            fields=[
                ('StaffId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=20)),
                ('Date_of_Birth', models.DateField()),
                ('BloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=20)),
                ('EmailId', models.EmailField(max_length=254)),
                ('phone_Number', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('Login', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.login')),
                ('Role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.role')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestReport',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('Findings', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.appointment')),
                ('LabTesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtechnicianApp.labtesting')),
                ('LabTechnician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labtechnicianApp.staffmanage')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='Technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labtechnicianApp.staffmanage'),
        ),
    ]
