# Generated by Django 5.2 on 2025-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtechnicianApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableLabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minValue', models.CharField(max_length=50)),
                ('maxValue', models.CharField(max_length=50)),
            ],
        ),
    ]
