# Generated by Django 5.2 on 2025-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtechnicianApp', '0002_availablelabtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablelabtest',
            name='id',
        ),
        migrations.AddField(
            model_name='availablelabtest',
            name='AvailableLabTestId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
