# Generated by Django 5.1.7 on 2025-04-03 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0002_alter_login_password_alter_signup_emailid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='EmailId',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='login',
            name='Role',
        ),
        migrations.AddField(
            model_name='login',
            name='LastLogin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='Signup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clinicapp.signup'),
        ),
    ]
