# Generated by Django 5.1.7 on 2025-04-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0003_remove_login_emailid_remove_login_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='LabDepartment',
        ),
        migrations.AddField(
            model_name='labtest',
            name='LabDevice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinicapp.labdevice'),
        ),
        migrations.DeleteModel(
            name='LabDepartment',
        ),
    ]
