# Generated by Django 5.1.7 on 2025-04-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0005_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='staffmanage',
            name='Login',
        ),
    ]
