# Generated by Django 5.1.7 on 2025-04-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0006_remove_doctor_userid_remove_staffmanage_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinicapp.role'),
        ),
    ]
