# Generated by Django 5.1.7 on 2025-04-06 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0007_doctor_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='PatientDetails',
        ),
        migrations.RemoveField(
            model_name='appointmentbill',
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='labtesting',
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='labtestreport',
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='LabTesting',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='Prescription',
        ),
        migrations.RemoveField(
            model_name='patienthistory',
            name='Consultation',
        ),
        migrations.RemoveField(
            model_name='labbill',
            name='LabTest',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='LabDevice',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='Technician',
        ),
        migrations.RemoveField(
            model_name='labtesting',
            name='Test',
        ),
        migrations.RemoveField(
            model_name='labtestreport',
            name='LabTesting',
        ),
        migrations.RemoveField(
            model_name='labtestreport',
            name='LabTechnician',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='Pharm',
        ),
        migrations.RemoveField(
            model_name='pharmbill',
            name='Pharmacist',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='Medicine',
        ),
        migrations.AlterField(
            model_name='batch',
            name='Pharm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_batches', to='Clinicapp.pharm'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_doctors', to='Clinicapp.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_doctors', to='Clinicapp.role'),
        ),
        migrations.AlterField(
            model_name='login',
            name='Signup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='Clinicapp.signup'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='Clinicapp.role'),
        ),
        migrations.AlterField(
            model_name='staffmanage',
            name='Role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_staff', to='Clinicapp.role'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PatientDetails',
        ),
        migrations.DeleteModel(
            name='AppointmentBill',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='PatientHistory',
        ),
        migrations.DeleteModel(
            name='LabBill',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
        migrations.DeleteModel(
            name='LabTesting',
        ),
        migrations.DeleteModel(
            name='LabTestReport',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
        migrations.DeleteModel(
            name='PharmBill',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
