# Generated by Django 5.1.7 on 2025-04-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0008_remove_appointment_doctor_and_more'),
    ]

    operations = [
    ]
