# Generated by Django 5.1.7 on 2025-04-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinicapp', '0009_auto_20250406_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labdevice',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pharm',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmanage',
            name='Date_of_Joining',
            field=models.DateField(default='2025-12-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffmanage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='labdevice',
            name='Status',
            field=models.CharField(choices=[('working', 'working'), ('undermaintenance', 'undermaintenance'), ('standby', 'standby'), ('outoforder', 'outoforder')], default='working', max_length=50),
        ),
    ]
