# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ReceptionistApp', '0002_remove_batch_pharm_remove_consultation_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorinform',
            fields=[
                ('informId', models.AutoField(primary_key=True, serialize=False)),
                ('DoctorName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestReport',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('Findings', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('RecordId', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnosis', models.TextField()),
                ('Treatment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('Frequency', models.CharField(max_length=100)),
                ('Dosage', models.CharField(max_length=100)),
                ('No_of_Days', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('ConsultantId', models.AutoField(primary_key=True, serialize=False)),
                ('Notes', models.TextField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='ReceptionistApp.appointment')),
            ],
        ),
    ]
