# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinicapp', '0010_doctor_date_labdevice_date_pharm_date_and_more'),
        ('Doctorapp', '0001_initial'),
        ('ReceptionistApp', '0002_remove_batch_pharm_remove_consultation_appointment_and_more'),
        ('labtechnicianApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='LabTesting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='labtechnicianApp.labtest'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctordetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctorapp.consultation'),
        ),
        migrations.AddField(
            model_name='doctorinform',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DOctor_specialist', to='Clinicapp.department'),
        ),
        migrations.AddField(
            model_name='labtestreport',
            name='Appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='ReceptionistApp.appointment'),
        ),
        migrations.AddField(
            model_name='labtestreport',
            name='LabTesting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='labtechnicianApp.labtest'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='Consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='Doctorapp.consultation'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='doctorname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctorapp.doctorinform'),
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctorapp.labtestreport'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ReceptionistApp.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='Medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_medicines', to='Clinicapp.pharm'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='Prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='Doctorapp.prescription'),
        ),
    ]
