# Generated by Django 5.1.7 on 2025-04-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctorapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='doctordetail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Doctorapp.doctorinform'),
        ),
    ]
