# Generated by Django 5.1.7 on 2025-04-12 13:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinicapp', '0010_doctor_date_labdevice_date_pharm_date_and_more'),
        ('ReceptionistApp', '0002_remove_batch_pharm_remove_consultation_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('PharmId', models.AutoField(primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_orders', to='ReceptionistApp.appointment')),
                ('Pharm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_pharmacists', to='Clinicapp.pharm')),
            ],
        ),
        migrations.CreateModel(
            name='PharmBill',
            fields=[
                ('BillId', models.AutoField(primary_key=True, serialize=False)),
                ('Bill_No', models.IntegerField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('GST', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('FinalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacistapp.pharmacist')),
                ('patientinform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReceptionistApp.patientdetails')),
            ],
        ),
    ]
