# Generated by Django 5.2 on 2025-04-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmbill',
            name='FinalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pharmbill',
            name='GST',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
